### ISSUE TITLE
Fix a broken logo

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#1]
Logo we're currently using is incorrectly formatted for some reason and looks weird.
![Screenshot 2020-04-04 at 19 14 03](https://user-images.githubusercontent.com/36959754/78457201-bca90c00-76a8-11ea-8bba-f4f44cb2f8ef.png)
![Screenshot 2020-04-04 at 19 15 13](https://user-images.githubusercontent.com/36959754/78457202-bd41a280-76a8-11ea-9b1e-4f9b118d5354.png)

Logos located here https://github.com/btcpayserver/btcpayserver-media

**Comment by joerlop** [comment]
Fixed with last commit
