### ISSUE TITLE
New entry submission - Blocksdemy/AcceptBTC Tech

### ISSUE THREAD

**Issue by Blockgazer** [btcpayserver/directory.btcpayserver.org#103]
New submission:

Name: Blocksdemy/AcceptBTC Tech
Url: https://blocksdemy.xyz/merchants/
Type: hosts
Description: Offering Btcpayserver to Online and Offline Stores. We charge something small to be able maintain our hosting.

**Comment by Zaxounette** [comment]
@Blockgazer I'll add your website in the next batch, but you really really need to do something about the BTCPay Server video you embedded on that page.
It launches automatically, with sound at 400% and you can stop/pause it.

**Comment by Blockgazer** [comment]
Ok
