### ISSUE TITLE
New entry submission - CTRL Pew

### ISSUE THREAD

**Issue by ctrlpew** [btcpayserver/directory.btcpayserver.org#118]
New submission:

Name: CTRL Pew
Url: https://shop.ctrlpew.com
Type: merchants - 3D printing
Description: We sell patches and such related to 3D printing guns :DWe dont sell 3D printed guns...yetWe do support developers who are designing and printing guns.

**Comment by Zaxounette** [comment]
hi @ctrlpew !

shop.ctrlpew.com does not work.
I expect the actual link is ctrlpew.com/shop ?
