### ISSUE TITLE
New entry submission - Crafts For Sats

### ISSUE THREAD

**Issue by beeforbacon** [btcpayserver/directory.btcpayserver.org#120]
New submission:

Name: Crafts For Sats
Url: craftsforsats.com
Type: apps
Description: Unique hand made crafts and decorations for many occasions.

**Comment by Zaxounette** [comment]
Hi @beeforbacon ,

That website has already been listed in the directory :)

![Screenshot_6](https://user-images.githubusercontent.com/51208677/91639903-2f30d480-ea1a-11ea-8141-6b577e72dd4f.jpg)

**Comment by Zaxounette** [comment]
Closing since it's a duplicate.
