### ISSUE TITLE
New entry submission - IntiCoin

### ISSUE THREAD

**Issue by cctvradio** [btcpayserver/directory.btcpayserver.org#123]
New submission:

Name: IntiCoin
Url: https://inticoin.mas.tienda
Type: apps
Description: Venta y Compra de Bitcoin, Ethereum, Bitcoin Cash, Litecoin así como Compra y Centra de nuestra crypto IntiCoin

**Comment by Zaxounette** [comment]
Hi @cctvradio  !

The directory is all about showcasing the different ways people use BTCPayServer.

Can you provide the actual URL where your instance is hosted, or a screen of the checkout if you use it for checkout ?
Or any other link for a BTCPay Server hosted app, crowdfund etc ...

Doesn't need to be unique, just needs to actually use BTCPay Server in a way or another.

Thanks,
Zaxounette.

**Comment by Zaxounette** [comment]
FYI, will close this issue after 20 days without an answer.

**Comment by Zaxounette** [comment]
Closing for lack of response.
