### ISSUE TITLE
New entry submission - GEOVANNY QUIROGA

### ISSUE THREAD

**Issue by GEOVANNYQUIROGA** [btcpayserver/directory.btcpayserver.org#127]
New submission:

Name: GEOVANNY QUIROGA
Url: https://tienda.p4s.co/geovannyquiroga
Type: merchants - fashion
Description: Somos una empresa punta de lanza en términos de mercado y moda, procurando en cuanto a nuestros empleados dar excelencia en todo aspecto y así mismo lograr productos que estén a la vanguardia en calidad, diseño, precio.

**Comment by Zaxounette** [comment]
Hi @GEOVANNYQUIROGA !

The directory is all about showcasing the different ways people use BTCPayServer.

Can you provide the actual URL where your instance is hosted, or a screen of the checkout if you use it for checkout ?
Or any other link for a BTCPay Server hosted app, crowdfund etc ...

Doesn't need to be unique, just needs to actually use BTCPay Server in a way or another.

Thanks,
Zaxounette.

**Comment by Zaxounette** [comment]
Closing for lack of response.

**Comment by GEOVANNYQUIROGA** [comment]
Buenas noches que pena no entiendo a que se refiere...
