### ISSUE TITLE
Remove Scrollbar on sidebar

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#13]
A scrollbar at the bottom does not look pretty and we should consider removing it, unless there's a specific reason why we have it? @joerlop ?
![Image Pasted at 2020-4-10 10-26](https://user-images.githubusercontent.com/36959754/78977229-1467cd00-7b18-11ea-95c3-f0a259d9929f.png)

**Comment by joerlop** [comment]
Think it's fixed. Will need to see if it is when site is redeployed.

**Comment by joerlop** [comment]
Done
