### ISSUE TITLE
New entry submission - BTCPay Merchant

### ISSUE THREAD

**Issue by evolve-tm** [btcpayserver/directory.btcpayserver.org#151]
New submission:

Name: BTCPay Merchant
Url: https://btcpaymerchant.com/Account/Login
Type: hosts
Description: btcpaymerchant.com is a free, BTCPay Server hosting provider for stores, non-profits, or anyone that wants to accept bitcoin.

**Comment by Zaxounette** [comment]
Hi @evolve-tm !

I'm getting an invalid certificat on the full HTTPS address `https://www.btcpaymerchant.com/`
Worked fine a few hours ago.

**Comment by evolve-tm** [comment]
Sorry I am not sure what happened but I think this should work now:
https://btcpaymerchant.com/Account/Login

**Comment by evolve-tm** [comment]
Can we delete this? Our btcpayserver doesn't work right now so we wouldn't want people using it. Is it an issue if we close our instance
