### ISSUE TITLE
New entry submission - SELLBITFAST

### ISSUE THREAD

**Issue by nwatarali** [btcpayserver/directory.btcpayserver.org#157]
New submission:

Name: SELLBITFAST
Url: https://btc.sellbitfast.com
Type: hosts
Description: Allowing Merchants Globally to accept and build their online store and accept cryptocurrency as a form of payment targeting Africa.

**Comment by Kukks** [comment]
This is just a pos app with no descriptions or anything. NACK on adding this to the list

**Comment by pavlenex** [comment]
@Kukks We do add apps to the list.

**Comment by Zaxounette** [comment]
@nwatarali Thanks for your submission ! 

You stated the type of your submission being `host`. Can you link us to your hosting instance, or the webfront before it ?
Tried `sellbitfast.com` without the subdomain `btc` but got an unresolved.

**Comment by nwatarali** [comment]
> @nwatarali Thanks for your submission !
> 
> You stated the type of your submission being `host`. Can you link us to your hosting instance, or the webfront before it ?
> Tried `sellbitfast.com` without the subdomain `btc` but got an unresolved.

this is a work in progress and will be resolved, thanks

**Comment by Zaxounette** [comment]
> this is a work in progress and will be resolved, thanks

Understood.

I'll close this submission for now, and you can re-submit when you're ready :) 
See you soon !
