### ISSUE TITLE
New entry submission - Axarquia Informatica

### ISSUE THREAD

**Issue by jomagalo** [btcpayserver/directory.btcpayserver.org#163]
New submission:

Name: Repuestos Tv
Url: https://btcpay.dontv.es/apps/3YubHJCEzTvxnz91p3aWqnQ6Bcyh/pos
Type: merchants - electronics
Description: Sale of spare parts for televisions and induction and ceramic hobs.

**Comment by Zaxounette** [comment]
Hi @jomagalo !

I noticed you didn't change the products descriptions. They still read as if they were the default Tea products.
You submission will still be approved, I just wanted give you have some time to modify this before including your shop into the Directory.

![sdWRAhFtST](https://user-images.githubusercontent.com/51208677/99888735-34837100-2c4f-11eb-9bc0-31dd2efadd3f.png)

Zax.

**Comment by jomagalo** [comment]
The description of the products are already updated. I would also like to include another url that is the main website. 

Thank you

New submission:

Name: Repuestos Tv
Url: https://www.axarquiainformatica.com/
Type: merchants - electronics
Description: Venta de recambios para televisores y vitrocerámicas. Más de 10 años de experiencia en online.

**Comment by Zaxounette** [comment]
@jomagalo I added your first entry request.

I didn't add (yet) the second one, since when testing the checkout process, I only had the paypal payment proposed, nothing relating to Bitcoin or BTCPay Server.

**Comment by jomagalo** [comment]
We have not activated the plugin yet since the node is 76% synchronized. In a few hours it will be 100% available. We are going to leave it activated at this time so you can see how it works.

**Comment by Zaxounette** [comment]
Okay noted. Will retry tomorrow night.

**Comment by jomagalo** [comment]
OK thank you very much

**Comment by jomagalo** [comment]
The node is 100% in sync. You can review the site whenever you want.

New submission:

Name: Axarquia Informatica
Url: https://www.axarquiainformatica.com/
Type: merchants - electronics
Description: Venta de recambios para televisores y vitrocerámicas. Disponemos de repuestos nuevos y usados. Más de 10 años trabajando con nuestros clientes avalan nuestros productos y experiencia.
