### ISSUE TITLE
New entry submission - MANO DI FILI

### ISSUE THREAD

**Issue by MDFshop** [btcpayserver/directory.btcpayserver.org#166]
New submission:

Name: MANO DI FILI
Url: https://manodifili.com/
Type: merchants - fashion
Description: MANO DI FILI is one of the firsts fashion shops to accept crypto-pay on Spain.

**Comment by Zaxounette** [comment]
Website not open yet.

@MDFshop please reply to this message once your website has been open to the public eyes. I'll then re-open this submission.

Thanks,
Zax.

**Comment by MDFshop** [comment]
This 27 the shop will open.
