### ISSUE TITLE
New entry submission - Bitcoin Ornaments

### ISSUE THREAD

**Issue by JaphyHigg** [btcpayserver/directory.btcpayserver.org#167]
New submission:

Name: Bitcoin Ornaments
Url: www.BitcoinOrnaments.com
Type: merchants - 3D printing
Description: Resin 3D Printed Bitcoin Ornaments -Shipping within the US only-

**Comment by Zaxounette** [comment]
@JaphyHigg Approved.

You can delete the order with the following email: `BTCPayServer_directory@test.com`
