### ISSUE TITLE
New entry submission - Crypto.ba

### ISSUE THREAD

**Issue by Ruxiol** [btcpayserver/directory.btcpayserver.org#174]
New submission:

Name: Crypto.ba
Url: https://rxcpay.crypto.ba
Type: non-profits
Description: Crypto.ba is Balkan based blockchain educational forum that is providing BTCPAY services for free!

----
EDIT @Zaxounette : Updated the https link to reflect user comment.

**Comment by l33d4n** [comment]
@Ruxiol Looks like you have some issues with the SSL certificate.

https://www.sslshopper.com/ssl-checker.html#hostname=https://pay.crypto.ba/

![image](https://user-images.githubusercontent.com/8020386/102483519-d441ec80-409f-11eb-8799-212a9073e616.png)

**Comment by Ruxiol** [comment]
> 
> 
> @Ruxiol Looks like you have some issues with the SSL certificate.
> 
> https://www.sslshopper.com/ssl-checker.html#hostname=https://pay.crypto.ba/
> 
> ![image](https://user-images.githubusercontent.com/8020386/102483519-d441ec80-409f-11eb-8799-212a9073e616.png)

How can i request new certificate? Its very strange that this is happening

**Comment by l33d4n** [comment]
The quickest and easiest way is to contact your hosting provider and request to set an additional SSL certificate for the subdomain.

**Comment by Zaxounette** [comment]
This has already been discussed in the chat. [Link 1](https://chat.btcpayserver.org/btcpayserver/pl/gua7s8kozbnm7jxex61j4zt4xh/) / [Link 2](https://chat.btcpayserver.org/btcpayserver/pl/3dcf1banmffq8nqqw6g3ky5b4y/).

Please keep the support discussions in the chat. I'll wait to see if your issue is fixed before approving.

**Comment by Ruxiol** [comment]
Ok its done now :) 

BTCPay on brand new hosting and server!

Open for everyone to use for FREE!

New submission:

Name: Crypto.ba
Url: https://rxcpay.crypto.ba
Type: non-profits
Description: Crypto.ba is Balkan based blockchain educational forum that is providing BTCPAY services for free!
