### ISSUE TITLE
New entry submission - BTCPayprovider.it

### ISSUE THREAD

**Issue by wispmanager** [btcpayserver/directory.btcpayserver.org#177]
New submission:

Name: BTCPayprovider.it
Url: www.btcpayprovider.it
Type: services
Description: BTCPay Hosting Provider Italia

----
EDIT by @Zaxounette : Changed subtype to `services` from `hosts`

**Comment by Zaxounette** [comment]
Hi @wispmanager !

As from what I gather from your website (translated to my language), you are not so much a host but more of a service provider.
Can you confirm ?

**Comment by wispmanager** [comment]
Yes, I confirm. The hosting service provider Btcpay is www.wispay.it cordially JosephIl 17 dic 2020 17:03, Zaxounette <notifications@github.com> ha scritto:
Hi @wispmanager !
As from what I gather from your website (translated to my language), you are not so much a host but more of a service provider.
Can you confirm ?

**Comment by wispmanager** [comment]
Good morning
I confirm that we are a blockchain IT services company and we are also
hosting Btcpay providers, this is the address of our Btcpay server
www.wispay.it

Cordially
Joseph

Il giorno gio 17 dic 2020 alle ore 17:03 Zaxounette <
notifications@github.com> ha scritto:
