### ISSUE TITLE
New entry submission - bitpaint

### ISSUE THREAD

**Issue by bitpaint** [btcpayserver/directory.btcpayserver.org#180]
New submission:

Name: bitpaint
Url: https://btcpay177475.lndyn.com/
Type: non-profits
Description: Support bitpaint with BTCPay, he create bitcoin street art & VR worlds

**Comment by Zaxounette** [comment]
You are already in the directory my good 'sir ! =)

https://github.com/btcpayserver/directory.btcpayserver.org/blob/997deefa78d134c111bf50db0649c937e4b98749/src/components/Directory/List.js#L1301-L1305

I'll close this :)

**Comment by bitpaint** [comment]
> You are already in the directory my good 'sir ! =)
> 
> https://github.com/btcpayserver/directory.btcpayserver.org/blob/997deefa78d134c111bf50db0649c937e4b98749/src/components/Directory/List.js#L1301-L1305
> 
> I'll close this :)

Hey Zax, I just updated the domain name to https://btcpay.bitpaint.club , can you update it, too?
