### ISSUE TITLE
New entry submission - Consignator

### ISSUE THREAD

**Issue by zologic** [btcpayserver/directory.btcpayserver.org#183]
New submission:

Name: Consignator
Url: https://consignator.online
Type: hosts
Description: Consignator is the first European One Stop Shop bridge between EU and non-EU merchants allowing dropshipping  and  C2C transactions  between Layer 2 and BTC.

**Comment by Zaxounette** [comment]
Hi @zologic !

The link you provided goes to a BTCPay Server cart style checkout, that's fine.
But there are still the default Tea items listed along-side your product.

Zax.
