### ISSUE TITLE
New entry submission - CryptoWebHost

### ISSUE THREAD

**Issue by civa** [btcpayserver/directory.btcpayserver.org#190]
New submission:

Name: CryptoWebHost
Url: https://cryptowebhost.com
Type: merchants - domains-hosting-vpns
Description: Host like a Pro  with CryptoWebhost- No.1 Offshore Web Hosting Company. Buy VPS and VPN with Cryptocurrency .

**Comment by Zaxounette** [comment]
Hi @civa !

The directory is intended for websites that actually use BTCPay Server.
I am unable to verify that it's the case for this website.

On checkout, the payment options are either `ETH` or `mycryptopay`, the latter being unaccessible.

Can you provide more info, screenshots ? Something ?

Thanks,
Zaxounette.

**Comment by Zaxounette** [comment]
No response to question in a week.

Closing this.
