### ISSUE TITLE
[Feature] Add icon with onion url hyperlink

### ISSUE THREAD

**Issue by MaxHillebrand** [btcpayserver/directory.btcpayserver.org#199]
Currently the url is displayed as the hyperlink over the name of the merchant. Thus there is only one url field possible to fill out, usually the clearnet site is most reasonable to input.

It would be nice to have an option to add the onion url as well. This could be displayed by a hyperlinked Tor onion icon next to the name of the merchant.

**Comment by Zaxounette** [comment]
Thanks Max for the feature request ! 

Will ping @dennisreimann for this, since he's the master of theses matters.

**Comment by dennisreimann** [comment]
Yep, sounds good.

**Comment by vaibhavgarg237** [comment]
_**Added onion URL icon in front of titles of organizations with beautiful bounce and flash animations.**_

-  ### Sample Image for Tor-Icon
![image](https://user-images.githubusercontent.com/67408018/192119291-23ed6b26-3f0c-4065-a491-53e49ccc7bae.png)

-  ### Bounce animation + Flash animation on hover over Tor-Icon Video
https://user-images.githubusercontent.com/67408018/192119487-48b82b47-99c2-4e77-8114-c0b35310b0ac.mp4
