### ISSUE TITLE
[Feature] Add social media icons

### ISSUE THREAD

**Issue by MaxHillebrand** [btcpayserver/directory.btcpayserver.org#200]
Currently the url is displayed as the hyperlink over the name of the merchant. This is usually the merchants website.

It would be nice to be able to add social media links too. This could be displayed by a hyperlinked social media icon next to the name of the merchant.

related to #199.

**Comment by alEXE-tech** [comment]
I can take on this feature request if no one has been assigned to it yet.

**Comment by alEXE-tech** [comment]
Done and waiting on pull request review.

**Comment by pavlenex** [comment]
Thanks for tackling this one @alEXE-tech! 🚀
