### ISSUE TITLE
New entry submission - Ocean County Retina, PC

### ISSUE THREAD

**Issue by retinadoc** [btcpayserver/directory.btcpayserver.org#206]
New submission:

Name: Ocean County Retina, PC
Url: http://www.oceancountyretina.com
Type: apps
Description: Medical practice accepting payment in Bitcoin.

**Comment by Zaxounette** [comment]
Hey @retinadoc !

This directory is provided for businesses/individuals that accept payment using BTCPay Server.
I expect you don't bill online, but only in person.
Can you provide any means of proof that you're using BTCPay Server ? Screenshots are suffiscient.

**Comment by retinadoc** [comment]
Hi! I’m in the process of getting dynamic DNS set so I can do it from my website and out of my intranet. Once done I will update. I didn’t realize the dynamic DNS part beforehand. 

Haris I Amin, MD
OceanCountyRetina.com

**Comment by Zaxounette** [comment]
Hi ! 

Sure, no problem.
I'll leave this submission open for 7 more days to give you time.

If for whatever reason I close this before you have everything setup, feel free to open another submission when ready.

Zaxounette.

**Comment by retinadoc** [comment]
Hi guys,
So I got my website working and now users can pay via BTC on chain as well as lightning. The website is:
Www.oceancountyretina.com

Hope I can now be included on the list of businesses!

Haris I. Amin M.D.
Ocean County Retina, P.C.
