### ISSUE TITLE
New entry submission - Einundzwanzig

### ISSUE THREAD

**Issue by dennisreimann** [btcpayserver/directory.btcpayserver.org#207]
New submission:

Name: Einundzwanzig
Url: https://einundzwanzig.shop
Type: merchants - cryptocurrency-paraphernalia
Description: The Einundzwanzig Shop sells Bitcoin merchandising: Shirts, hoodies, coffee mugs, all the good stuff.

**Comment by Zaxounette** [comment]
'Sir, I don't speak your strange language.

I would ask for an official translation by a government appointed translator.

**Comment by dennisreimann** [comment]
@Zaxounette "If you don’t believe it or don’t get it, I don’t have the time to try to convince you, sorry."
