### ISSUE TITLE
New entry submission - LN Art Co.

### ISSUE THREAD

**Issue by lnartco** [btcpayserver/directory.btcpayserver.org#212]
New submission:

Name: LN Art Co.
Url: lnart.co
Type: merchants - art
Description: Historical works of art, beautifully printed on museum-grade Bamboo canvas. Exclusively via the bitcoin Lightning Network ⚡. Delivered worldwide.

**Comment by Zaxounette** [comment]
Hi ! 

Submission approved.
You can delete the order with the email btcpayserver@test.com

I'll add you to the directory.

Zax.
