### ISSUE TITLE
New entry submission - Movisalud

### ISSUE THREAD

**Issue by movisalud** [btcpayserver/directory.btcpayserver.org#214]
New submission:

Name: Movisalud
Url: www.movisalud.cl
Type: merchants - health-household
Description: House Doctors in Chile , Medicos a domicilio en Chile.

**Comment by Zaxounette** [comment]
Hey @movisalud !

Can you give me a link in your website, or a screenshot where BTCPay Server appears, or a mention of it appears ?

**Comment by Zaxounette** [comment]
Closing for lack of response.
