### ISSUE TITLE
New entry submission - Hyke 

### ISSUE THREAD

**Issue by Tamicaa** [btcpayserver/directory.btcpayserver.org#221]
New submission:

Name: Hyke & Byke

URL: https://www.hykeandbyke.com/

Description:
Hyke & Byke was founded with one core mission: to get backpackers and outdoor enthusiasts premium, lightweight, comfortable gear for sleeping outside -- at the best price possible.

**Comment by Zaxounette** [comment]
Type: Merchant
Subtype: holiday-travel
