### ISSUE TITLE
New entry submission - Sayyaf69sy

### ISSUE THREAD

**Issue by S69y** [btcpayserver/directory.btcpayserver.org#224]
@[https://musician-208.business.site/?utm_source=gmb&utm_medium=referral](https://g.co/kgs/cza6sd) 
![Uploading  #image.jpg…]()
 New  `#submission:`

Name: Sayyaf69sy
Url: https://g.co/kgs/cza6sd
Type: apps
Description: sayyaf_69@example.com

**Comment by Zaxounette** [comment]
Hi !

We require a proper description and a proper website address.
Please edit accordingly.

**Comment by Zaxounette** [comment]
Closing for lack of response.
