### ISSUE TITLE
New entry submission - Optica Top Vision

### ISSUE THREAD

**Issue by opticatopvision** [btcpayserver/directory.btcpayserver.org#234]
New submission:

Name: Optica Top Vision
Url: https://www.topvision.com.ar
Type: merchants - fashion
Description: Óptica Top Visión es una empresa marplatense con 13 años de trayectoria, dedicada al bienestar y cuidado de su visión. Nos especializamos en anteojos de receta, de sol, Lentes de contacto estéticos y reparaciones. Aceptamos pagos con USDT, DAI, USDC, BUSD

**Comment by Zaxounette** [comment]
Hi @opticatopvision !

Could you edit your submission and rewrite it in English?

Thanks!

**Comment by Zaxounette** [comment]
Closed for lack of response.
