### ISSUE TITLE
New entry submission - KryptoDoupě

### ISSUE THREAD

**Issue by gorrdy** [btcpayserver/directory.btcpayserver.org#235]
New submission:

Name: KryptoDoupě
Url: https://www.kryptodoupe.cz/
Type: apps
Description: Portál pro začínající bitcoinery.

**Comment by Zaxounette** [comment]
Hi @gorrdy , can you edit your submission and rewrite it in English?

Thanks.

**Comment by Zaxounette** [comment]
Closing for lack of response.
