### ISSUE TITLE
New entry submission - Cripto PC

### ISSUE THREAD

**Issue by carloscripto** [btcpayserver/directory.btcpayserver.org#238]
New submission:

Name: Cripto PC
Url: http://www.criptopc.com
Type: merchants - electronics
Description: Welcome to Criptopc store! We sell electronic devices, gamer products, cell phone accessories and technology in general. Maintenance of computers and printers, technical support. WE RECEIVE PAYMENTS WITH BITCOIN AND CRYPTOCURRENCY.

**Comment by Zaxounette** [comment]
This is a directory for merchant websites that use BTCPay Server to accept payments, not CoinPayments.net
