### ISSUE TITLE
New entry submission - ij.start.canon

### ISSUE THREAD

**Issue by MarcoWebPortal** [btcpayserver/directory.btcpayserver.org#269]
New submission:

Name: ij.start.canon
Url: https://xn--ijstrtcnonset-6dbd.ijstartuk.com/
Type: apps
Description: Ij.start.canón is the official website of Canón. Do you want to know the benefits of this website? If yes, then you must know that it provides you with a quick setup guide. Visit: Visit: https://xn--jstrtcanopixma-xgb6o.ijstartij.co.uk/

**Comment by Zaxounette** [comment]
Looks sus AF.
