### ISSUE TITLE
New entry submission - SuperAtic ɪɴᴄ.

### ISSUE THREAD

**Issue by SuperAtic** [btcpayserver/directory.btcpayserver.org#283]
New submission:

Name: SuperAtic ɪɴᴄ.
Url: https://SuperAtic.com
Type: merchants - cryptocurrency-paraphernalia
Description: Design & Technology Consultancy

**Comment by pavlenex** [comment]
Don't see btcpay anywhere, if the website shows it pelase share a link, seems like a placeholder page for now.
