### ISSUE TITLE
New entry submission - BTCLTC host

### ISSUE THREAD

**Issue by plexifyme** [btcpayserver/directory.btcpayserver.org#286]
New submission:

Name: BTCLTC host
Url: btcpay499366.lndyn.com
Type: apps
Description: is a BTCPay Server hosting provider.I have added support for BTC , LTC , DOGE , BTC Lightning , LTC LightningDepending upon user requests and budget i will add support for lot more hosts

**Comment by pavlenex** [comment]
Doesn't work. If you come back online, please re-open the issue.
