### ISSUE TITLE
Einreichung eines neuen Eintrags - K&M-Projektplan GmbH

### ISSUE THREAD

**Issue by jungusemlevve** [btcpayserver/directory.btcpayserver.org#304]
Neue Einreichung: Einreichen eines neuen Eintrags im BTCPay Server Verzeichnis
Bei Rückfragen: admin@km-projektplam.de
Name: K&M-Projektplan GmbH

**Comment by pavlenex** [comment]
Please re-submit with a proper website URL I cannot find your website.

**Comment by jungusemlevve** [comment]
Hallo,

https://www.km-projektplan.de
Am 4. Apr. 2022, 12:22 +0200 schrieb btcpayserver/directory.btcpayserver.org ***@***.***>:
> Please re-submit with a proper website URL I cannot find your website.

**Comment by pavlenex** [comment]
I am having problems finding btcpay on the site, can you screenshot or point me to a link , I don't speak German.

**Comment by jungusemlevve** [comment]
In Anlage

https://www.km-projektplan.de/bezahlen-mit-bitcoin/

Ich habe Ihnen soeben eine zweite Anfrage geschickt über einen Verein Biker for Kids. e.V. als Spendenseite

https://www.km-projektplan.de/biker-for-kids-cologne-e-v/
Am 4. Apr. 2022, 12:45 +0200 schrieb Pavlenex ***@***.***>:
