### ISSUE TITLE
New entry submission - Biker for Kids e.V.

### ISSUE THREAD

**Issue by jungusemlevve** [btcpayserver/directory.btcpayserver.org#306]
New submission:

Name: Biker for Kids e.V.
Url: https://www.km-projektplan.de/biker-for-kids-cologne-e-v/
Type: non-profits
Description: Biker For Kids Cologne e.V. freut sich über Ihre Spende per Bitcoin oder Lightning.
Herzlich willkommen bei den Biker-Weihnachtsmännern. Jedes Jahr in der Vorweihnachtszeit und zu besonderen Anlässen, sind die Weihnachtsmänner unterwegs, um Spenden

**Comment by pavlenex** [comment]
This is tallycoin not btcpay server.

**Comment by jungusemlevve** [comment]
????

https://www.km-projektplan.de/biker-for-kids-cologne-e-v/

in Anlage
Am 4. Apr. 2022, 13:04 +0200 schrieb Pavlenex ***@***.***>:
