### ISSUE TITLE
New entry submission - Langua.me english courses 

### ISSUE THREAD

**Issue by chrl57l4n** [btcpayserver/directory.btcpayserver.org#312]
New submission:

Name: Langua.me english courses 
Url: https://langua.me/
Type: apps
Description: Курсы английского языка онлайн в КазахстанеМы предлагаем курсы английского для детей и взрослых от начинающих до продвинутых уровней, включая IELTS и TOEFL.

**Comment by pavlenex** [comment]
Don't see btcpay option, please provide a link/screenshoot and we'll re-consider.
