### ISSUE TITLE
New entry submission - NameCheap

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#315]
New submission:

Name: NameCheap
Url: http://namecheap.com
Type: apps
Description: Namecheap began in 2000 with a mission to deliver the best domains at the best prices with the best service. Since then we’ve added hosting, security, managed WordPress, and a whole range of innovations to our platform.

**Comment by l33d4n** [comment]
NameCheap was my first PR here - #133 ;)

**Comment by pavlenex** [comment]
Sorry about that. Must have missed it.
