### ISSUE TITLE
Add instructions on how to do a PR for adding an entry

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#32]
We should add instructions on how to add a pull request for submitting a new entry to readme.md

**Comment by dennisreimann** [comment]
Maybe we can use the [issue/pr templates](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) to formalize the submission?

**Comment by pavlenex** [comment]
Sure! I guess that's another issue, can you open an issue for that for people who'd like to add submission via gh. Our process is already formalized through directory.

**Comment by pavlenex** [comment]
What I'd like to address in this issue is instruction on how to add a pull request for an entry not an issue.
