### ISSUE TITLE
New entry submission - bitcoin:bc1qnrtw4uf3cqsfq3w7xm79dgz3xy38995k6zclk8

### ISSUE THREAD

**Issue by badassboo** [btcpayserver/directory.btcpayserver.org#326]
New submission:

Name: bitcoin:bc1qnrtw4uf3cqsfq3w7xm79dgz3xy38995k6zclk8
Url: bitcoin:bc1qnrtw4uf3cqsfq3w7xm79dgz3xy38995k6zclk8
Type: merchants - software-video-games
Description: Pay for software

**Comment by vaibhavgarg237** [comment]
It would be better to add the proper name instead of bitcoin address, please add the name of the business...
