### ISSUE TITLE
New entry submission - Wearepoint

### ISSUE THREAD

**Issue by M4x28** [btcpayserver/directory.btcpayserver.org#327]
New submission:

Name: Wearepoint
Url: https://beta.wearepoint.net/
Type: merchants - tools
Description: Vorremmo integrare pagamenti in crypto nel nostro sito web.

**Comment by phrazzld** [comment]
The link appears to be broken and I can't find anything else on this business.

I'm happy to open a PR with this change if you can supply a working link though!
