### ISSUE TITLE
New entry submission - BTCPayServer hosted by yohost.org

### ISSUE THREAD

**Issue by treasurehunter012** [btcpayserver/directory.btcpayserver.org#340]
New submission:

Name: BTCPayServer hosted by yohost.org          
Url: https://yohost.org/crypto-payment/          
Twitter: @yohostorg                    
Type: hosts          
Description: BTCPayServer hosted by yohost.org. We offer turn-key solution to accept Bitcoin on your website, including integration and module development.

**Comment by pavlenex** [comment]
Doesn't mention btcpay anywhere, please provide a proper link and we'll re open the submission.
