### ISSUE TITLE
New entry submission - BITSTREAM

### ISSUE THREAD

**Issue by atomics13** [btcpayserver/directory.btcpayserver.org#39]
New submission:

Name: BITSTREAM
Url: https://bitstream.video
Description: Create and schedule your live streaming events, set your price and get paid directly into your own wallet. No third parties, no fees. Working with BTCPay Server.
Type: Merchant - Streaming

**Comment by pavlenex** [comment]
@atomics13 Care to elaborate how is BTCPay Server connected to this? `Working with BTCPay Server`does it mean it just works with xpub or you use BTCPay in another way? Tested your site and it was unclear.

**Comment by atomics13** [comment]
Hello. Thanks for testing. The normal way, we create the store with the xpub so the webcaster can get paid by the viewers. I dont find any way to create the store and wallet via api in btcpay, the rest is via php api btcpay (bitpay) . You can watch the video if you want https://bitstream.video

**Comment by pavlenex** [comment]
Alright, understood , just wanted to check if you really use BTCPay Server, which after testing, I verified, you do. Cool service.

![Screenshot 2020-04-26 at 00 25 57](https://user-images.githubusercontent.com/36959754/80292166-a8f73f80-8754-11ea-9d04-b7ac4b4d8714.png)
