### ISSUE TITLE
New entry submission - Nodetech

### ISSUE THREAD

**Issue by nodetechio** [btcpayserver/directory.btcpayserver.org#413]
New submission:

Name: Nodetech          
Url: https://nodetech.io                              
Type: merchants - services          
Description: Our company specializes in offering innovative automation solutions, supported by artificial intelligence. Our focus is on time optimization and process control for companies and professionals. We help you get your time back.

**Comment by pavlenex** [comment]
Can you explain how you use btcpay and provide some proof, was unable to find it on the website.
