### ISSUE TITLE
New entry submission - Casbay

### ISSUE THREAD

**Issue by Nimbusoo** [btcpayserver/directory.btcpayserver.org#414]
New submission:

Name: Casbay          
Url: https://www.casbay.com                              
Type: merchants - domains-hosting-vpns          
Description: Casbay offers a wide range of hosting services, including domain registration, VPS, dedicated servers, and cloud solutions. Starting at $5.59 for the basic VPS plan.

**Comment by pavlenex** [comment]
Uses Coinbase commerce not btcpay.
