### ISSUE TITLE
discrepancy in Type in list.js and submission form results on GitHub

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#42]
## Plural vs Singular 
When user submit a submission over the website form, the type is `non-profit`, `host`, etc.
However in lists.js it's in plural `non-profits`, `hosts`.

While this is something a regular contributor can get used to, it may cause some issues and back and forth when someone tries to tackle an issue, so I suggest we standardize it.

@joerlop Perhaps there's a logic in here that I'm missing? I don't think it's a big deal and if there's logical explanation, I'm fine with it, we can see if it confuses people.
![1](https://user-images.githubusercontent.com/36959754/80286957-e1842280-872e-11ea-9cc4-26b381b6393d.PNG)
![2](https://user-images.githubusercontent.com/36959754/80286959-e21cb900-872e-11ea-9d49-3a83965cfdb2.PNG)

## Order or fields
Second, the type field in issue submission is 3rd
- Name 
- URL
- **Type**
- Description

Where as in submission form it's 4th

- Name 
- URL
- Description
- **Type**

Again this is not a big deal but it's kinda logical to have them in order so people can fill in data in the order when they're watching an issue.

**Comment by Zaxounette** [comment]
On the first issue, having a standard would be good. 
It would prevent typos.

BTW, if in list.js "host" is put in instead of "hosts", does the merchant get listed in the "hosts" category nonetheless ? Or does the typo prevent that ?
Same question for non-profit/non-profits.
