### ISSUE TITLE
New entry submission - GoGetFunding

### ISSUE THREAD

**Issue by sandip6030** [btcpayserver/directory.btcpayserver.org#425]
New submission:

Name: GoGetFunding          
Url: https://gogetfunding.com/crypto-crowdfunding-raise-money-in-bitcoin/          
Twitter: @GoGetFunding                    
Type: merchants - services          
Description: GoGetFunding is a fundraising website for personal causes. Established in 2011, we've now added Bitcoin payment integration (via BTCPay) to help more people around the world raise money more easily & with lower fees

**Comment by woutersamaey** [comment]
@pavlenex Sandip is a client of mine. I set up their BTCPay Server instance. They just wanna be in the directory of merchants using BTCPay. Is there an issue why they can't be included?

**Comment by woutersamaey** [comment]
Thanx Pav,

I can definately vouch. Great guys over there. True bitcoiners.

They mention Bitcoin on their website, but I agree, it doesn't say BTCPay Server explicitly:
https://gogetfunding.com/crypto-crowdfunding-raise-money-in-bitcoin/

They just got started. Maybe they'll mention it on next site update.
