### ISSUE TITLE
New entry submission - SmartSquare Tools

### ISSUE THREAD

**Issue by SmartSquareTools** [btcpayserver/directory.btcpayserver.org#442]
New submission:

Name: SmartSquare Tools          
Url: https://smartsquaretools.com/          
Twitter: @SmartSquareTool                    
Type: merchants - tools          
Description: We sell a patented rafter square for carpenters, floorers, and metalworkers that has a number of revolutionary features. Made in the USA.

**Comment by pavlenex** [comment]
Couldn't fidn btcpay in the checkout.

**Comment by SmartSquareTools** [comment]
When we received no mention or activity in the first months of setting up BTCPay, even from people who said they would tweet out recommendations, we could no longer afford it and shut it down entirely. Please remove us from any lists; we will not be supporting Bitcoin moving forward.
