### ISSUE TITLE
New entry submission - ManoKodu

### ISSUE THREAD

**Issue by manokodu** [btcpayserver/directory.btcpayserver.org#444]
New submission:

Name: ManoKodu          
Url: https://www.manokodu.net/                              
Type: merchants - services          
Description: ManoKodu provides an outlet for creativity and entertainment. The project features voice acting, conversation, music, and future endeavors in animation and gaming. It is a place to be free, reminisce, dream, and feel at home.

**Comment by pavlenex** [comment]
unclear if btcpay is being used, provide more steps how to verify and we can reconsider.
