### ISSUE TITLE
New entry submission - owncast hosting

### ISSUE THREAD

**Issue by roboco2022** [btcpayserver/directory.btcpayserver.org#450]
New submission:

Name: owncast hosting          
Url: https://owncasthosting.com/                              
Type: merchants - streaming          
Description: Do you think live streaming is just for influencers? Think again. Discover the innovative ways businesses are engaging audiences and driving growth with live streams. Take a peek into the future with our service.

**Comment by pavlenex** [comment]
I have no idea how to test if you're using BTCPay please post screenshots.
