### ISSUE TITLE
Visual issue in Darkmode.

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/directory.btcpayserver.org#51]
Found a visual issue in DarkMode on the directory website.
See screenshot below.

Category list is invisible except on mouseover.

Issue doesn't affect light mode.
Issue doesn't appear on Firefox, only on Chrome (Version 81.0.4044.122, up-to-date, cache deleted, cookies also)

![Screenshot_45](https://user-images.githubusercontent.com/51208677/80305297-49347f00-87bc-11ea-8317-2f92e2b7b73c.png)

**Comment by NicolasDorier** [comment]
ping @dennisreimann

**Comment by dennisreimann** [comment]
That must be a Windows-related bug, as it works on macOS.

<img width="419" alt="mac-chrome" src="https://user-images.githubusercontent.com/886/80317194-99cecb00-8802-11ea-8c5c-6a5e00d4d821.png">

We could try to set the background of the select element to `transparent`, but I doubt this will help.

**Comment by NicolasDorier** [comment]
![image](https://user-images.githubusercontent.com/3020646/80317367-5abe6b00-883e-11ea-80df-b77d8d4cc108.png)

**Comment by NicolasDorier** [comment]
interesting, this bug happen only on chrome, not firefox.

**Comment by pavlenex** [comment]
Can confirm that the issue only happens on Google Chrome, my version is `Version 81.0.4044.122 (Official Build) (64-bit)` On Firefox it works as it's intended. 

@joerlop any idea what may be the issue?

**Comment by NicolasDorier** [comment]
It seems to be only on Chrome only on Windows oO

**Comment by NicolasDorier** [comment]
ha, I found the culprit CSS

![image](https://user-images.githubusercontent.com/3020646/80317622-dbca3200-883f-11ea-913c-0e7fd6ce1393.png)
