### ISSUE TITLE
New entry submission - Seeders Instruments

### ISSUE THREAD

**Issue by wsmosheim** [btcpayserver/directory.btcpayserver.org#56]
New submission:

Name: Seeders Instruments
Url: seedersinstruments.com
Description: Seeders Instruments specializes in building handmade banjos and guitars. In the store you can also find strings, accessories, and cases, primarily for banjos but also for guitars, as well as one-of-a-kind art made in between instrument projects. 
Type: Merchant - Art

**Comment by Zaxounette** [comment]
![Screenshot_46](https://user-images.githubusercontent.com/51208677/80518832-4fc32200-8987-11ea-9372-5840e0c3a7f3.png)


Will add in next batch.
