### ISSUE TITLE
New entry submission - btcpay.bid

### ISSUE THREAD

**Issue by nakedgoat** [btcpayserver/directory.btcpayserver.org#58]
New submission:

Name: btcpay.bid
Url: https://btcpay.bid
Description: Assisting anyone wanting to accept BTC for donations, payments and etc on their website or in their storefront. 
Type: Host

**Comment by Zaxounette** [comment]
@nakedgoat The link is broken. Can you fix it so we can be assured BTCPayServer is actually used ?
Thanks :)

**Comment by nakedgoat** [comment]
yea I am having issues w/my proxy redirecting using the nginx docker and my severs, it’s crazy!! there’s no reason cannot run more nodes, will they pick each other up or I do I need to do untying should add multiple. nodes.

I will let you know when I have them back up, I’ve been trying to fix this for over an hour .. about to wipe the box and install a full version w/o docker!

**Comment by Zaxounette** [comment]
No problem.
Let me know when everything's resolved.

**Comment by nakedgoat** [comment]
Will do, what’s the best place to get some real time assistance, IRC? what/where is the main IRC server if there is one.


I will let you know, I’m standing up node2 now, hopefully that will work until I can get node 1 fixed.

**Comment by nakedgoat** [comment]
Hello Sir,

Its’ back up - it’s just now downloading the blockchain since it’s the new node, I suppose it’s going to take some time. Let me know if you need anything else, I’m going to work on the other node, which I suppose will be node2.btcpay.bid <http://node2.btcpay.bid/> , until I look into clustering.

**Comment by Zaxounette** [comment]
To many redirects, unable to access your website.

**Comment by nakedgoat** [comment]
Ok, so I removed the additional proxy I was using. I am still having issues however, I thought after installing on a clean machine took care of everything.  This morning it started again, the WEBUI goes down. I cannot tell if the backend is up but the docker instances are all running as far as I can tell.  After removing my CDN (Cloudflare) I am getting a 503 nginx error, checking the logs
I do not see anything at the moment in nginx, nginx-gen.  I se you just posted, I don't have any redirects at the moment I'll double check my old server for anything. I am in the Slack #help channel if it's easier.

**Comment by Zaxounette** [comment]
The link works, added it to the batch.
