### ISSUE TITLE
Add a "DYOR" message/warning.

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/directory.btcpayserver.org#64]
New submissions for the directory are added week after week.
There are now 150 merchants/apps/hosts registered on the directory.

We only check that the submission-ed website/app effectively uses BTCPayServer, but we cannot assure that it's legit or whatnot.

Some users could potentially think that by being listed, a website is curated and legit, which we can't guarantee.

A simple message (visible maybe at all times at the top of the directory website ?) could fix this.

If agreed, wording in the likes of the following could do the trick:
> This directory is provided for information purposes only. We do not guarantee the legitimacy of the websites listed here. Do Your Own Research.

Feedback appreciated !

**Comment by pavlenex** [comment]
Makes sense.

Where could this be added?

**Comment by Zaxounette** [comment]
> Where could this be added?

Maybe somewhere like this ?

![Screenshot_47](https://user-images.githubusercontent.com/51208677/81715578-adbc3300-9478-11ea-93be-bf55a47de892.png)

**Comment by pavlenex** [comment]
That looks too scary. 
It needs to be a subtle disclaimer, perhaps at the bottom IMO.

**Comment by Zaxounette** [comment]
I feel like if it was in the bottom it wouldn't serve as well ?

**Comment by Zaxounette** [comment]
As a subtle popup ?

![Screenshot_48](https://user-images.githubusercontent.com/51208677/81725640-6fc60b80-9486-11ea-9798-e4fc68523fce.png)

**Comment by pavlenex** [comment]
I feel like it's distracting from the main use-case of the web-page. IMO Disclaimers are there so nobody read them but you can tell people "we have a disclaimer for that", basically useless but needed.

**Comment by pavlenex** [comment]
I think adding a concise message that can fit into footer should be enough.

**Comment by Zaxounette** [comment]
> `This website does not use cookies nor collect personal data.`
> `Entries are self-submitted and provided for information purposes only.` or whatever

I like the wording of that !
