### ISSUE TITLE
New entry submission - TKS

### ISSUE THREAD

**Issue by bigsk1** [btcpayserver/directory.btcpayserver.org#67]
New submission:

Name: TKS
Url: https://thekratomsyndicate.com/
Description: Kratom teas, extracts and CBD
Type: Merchant - Health and Household

**Comment by bigsk1** [comment]
We have magneto 2 integration with btcpay server in checkout. 

You can see more about the btcpay integration here https://thekratomsyndicate.zendesk.com/hc/en-us/community/posts/360057668131-Bitcoin-invoice-now-working-in-checkout-

**Comment by Zaxounette** [comment]
Your cloudflare needs tweeking.

![Screenshot_49](https://user-images.githubusercontent.com/51208677/81833168-af9cf980-953f-11ea-84bb-8d3ba9635dbd.png)

**Comment by Zaxounette** [comment]
Your cloudflare needs tweeking.

![Screenshot_49](https://user-images.githubusercontent.com/51208677/81833369-e70ba600-953f-11ea-9a3a-7263e7f444a4.png)

**Comment by bigsk1** [comment]
> Your cloudflare needs tweeking.
> 
We have geo blocking enabled for some countries, as we only sell within USA. So it helps to keep those bad bots off the site.

**Comment by Zaxounette** [comment]
Understandable.
Switched my VPN to access.

Will add your submission in next batch.
