### ISSUE TITLE
New entry submission - BTC Factura

### ISSUE THREAD

**Issue by i2dor** [btcpayserver/directory.btcpayserver.org#68]
New submission:

Name: BTC Factura
Url: https://www.btcfactura.com/
Description: BTC Factura provides an easy way to pay your Romanian bills and services with Bitcoin, since 2016. Home of the largest  Bitcoin Lightning node in Romania.
Type: Merchant - Gift Cards

**Comment by Zaxounette** [comment]
Found BTCPay Woo-commerce plugin. Good to go ! 

I'll add you in the next batch.

**Comment by i2dor** [comment]
Many thanks to both of you, Vincent & Nedved!
