### ISSUE TITLE
New entry submission - Redneck Owned Inc.

### ISSUE THREAD

**Issue by snoowl26** [btcpayserver/directory.btcpayserver.org#71]
New submission:

Name: Redneck Owned Inc.
Url: KryptoLoki.com
Description: A low cost Krypto pay server who will work with anyone anywhere in the world if they want to deal in krypto currency.
Type: Merchant - Services

**Comment by pavlenex** [comment]
Invalid URL, please provide a working URL and a proof (screenshot or a link) that you use BTCPay Server so we can list you.

**Comment by snoowl26** [comment]
no problem had some server problems today so its not totally down loaded yet

**Comment by Zaxounette** [comment]
URL still not working.

Time to close ?

**Comment by snoowl26** [comment]
no im sure its not redneck owned inc.   Thats the parent comp to the url of
kryptoloki.com  which is the domain that the payserver is under.

**Comment by Zaxounette** [comment]
Well feel free to close this issue and submit another entry with the updated information.
