### ISSUE TITLE
Add a link to the instructions on how to run locally in main readme.md

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/directory.btcpayserver.org#74]
- [ ]  Add instructions in readme on how people can run directory locally.

**Comment by Zaxounette** [comment]
Yes please <3

**Comment by Zaxounette** [comment]
As per informations provided by @dennisreimann , setting up locally a directory is done with the same process as the documentations.

https://github.com/btcpayserver/btcpayserver-doc/#build-the-documentation-locally

The only prerequisite being having node.js installed.

**Comment by pavlenex** [comment]
The instructions are available here actually https://github.com/btcpayserver/directory.btcpayserver.org/tree/master/directory just need at least a link back in "Build the Directory Locally" section. Feel free to tackle it if you want @Zaxounette

**Comment by dennisreimann** [comment]
I‘d like to restructure the repo a bit once my two PRs are merged. Especially I think we should get rid of the directory folder, so that the structure resembles what we have in the website repo. 

I can take care of the instructions when doing that.

**Comment by pavlenex** [comment]
Sure, go ahead @dennisreimann
