### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/directory.btcpayserver.org#90]
https://merklesig.com/

**Comment by Zaxounette** [comment]
ACK.
Will remove in next batch.

**Comment by Zaxounette** [comment]
Gone through the list manually for broken links:

Will remove the following that are broken for whatever reason in addition to the one found by Kukks:

* https://golightning.club/
* https://internetsuper.store/
* https://thekratomsyndicate.com/
* https://whiterabbit.store/
* https://www.compudemano.com/
