### ISSUE TITLE
Update Pavlenex's donation link

### ISSUE THREAD

**Issue by Zaxounette** [btcpayserver/directory.btcpayserver.org#92]
from pavlenez.com to https://fund.btcpayserver.org/apps/3bfwsFviwBfERPQvgqFFoz4aD8RG/pos

@pavlenex do I update or will the link redirect to pavlenex.com at one point ?

**Comment by pavlenex** [comment]
You can update I won't be using that domain name anymore.

**Comment by Zaxounette** [comment]
ACK
